#############################################################################
# Makefile for building: monitor
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? ???. 24 16:38:50 2010
# Project:  monitor.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile monitor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I/usr/include/qwt-qt4 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -IprocessDialog -Iincludes -InewConfigDialog -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) `libusb-config --libs` -L/usr/lib -lQtGui -lQtCore -lpthread -lqwt-qt4
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mwindow.cpp \
		includes/dconfig.cpp \
		includes/dcurve.cpp \
		includes/dsaver.cpp \
		includes/dthread.cpp \
		includes/uhandler.cpp \
		newConfigDialog/configdialog.cpp \
		processDialog/processdialog.cpp moc_mwindow.cpp \
		moc_dcurve.cpp \
		moc_dsaver.cpp \
		moc_dthread.cpp \
		moc_uhandler.cpp \
		moc_configdialog.cpp \
		moc_processdialog.cpp
OBJECTS       = main.o \
		mwindow.o \
		dconfig.o \
		dcurve.o \
		dsaver.o \
		dthread.o \
		uhandler.o \
		configdialog.o \
		processdialog.o \
		moc_mwindow.o \
		moc_dcurve.o \
		moc_dsaver.o \
		moc_dthread.o \
		moc_uhandler.o \
		moc_configdialog.o \
		moc_processdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		monitor.pro
QMAKE_TARGET  = monitor
DESTDIR       = 
TARGET        = monitor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_configdialog.h ui_processdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: monitor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile monitor.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile monitor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/monitor1.0.0 || $(MKDIR) .tmp/monitor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/monitor1.0.0/ && $(COPY_FILE) --parents mwindow.h includes/dconfig.h includes/dcurve.h includes/dpack.h includes/dsaver.h includes/dthread.h includes/uhandler.h newConfigDialog/configdialog.h processDialog/processdialog.h .tmp/monitor1.0.0/ && $(COPY_FILE) --parents main.cpp mwindow.cpp includes/dconfig.cpp includes/dcurve.cpp includes/dsaver.cpp includes/dthread.cpp includes/uhandler.cpp newConfigDialog/configdialog.cpp processDialog/processdialog.cpp .tmp/monitor1.0.0/ && $(COPY_FILE) --parents mainwindow.ui newConfigDialog/configdialog.ui processDialog/processdialog.ui .tmp/monitor1.0.0/ && (cd `dirname .tmp/monitor1.0.0` && $(TAR) monitor1.0.0.tar monitor1.0.0 && $(COMPRESS) monitor1.0.0.tar) && $(MOVE) `dirname .tmp/monitor1.0.0`/monitor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/monitor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mwindow.cpp moc_dcurve.cpp moc_dsaver.cpp moc_dthread.cpp moc_uhandler.cpp moc_configdialog.cpp moc_processdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mwindow.cpp moc_dcurve.cpp moc_dsaver.cpp moc_dthread.cpp moc_uhandler.cpp moc_configdialog.cpp moc_processdialog.cpp
moc_mwindow.cpp: processDialog/processdialog.h \
		includes/dthread.h \
		includes/uhandler.h \
		includes/dpack.h \
		includes/dconfig.h \
		includes/dcurve.h \
		includes/dsaver.h \
		ui_processdialog.h \
		newConfigDialog/configdialog.h \
		ui_configdialog.h \
		ui_mainwindow.h \
		mwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mwindow.h -o moc_mwindow.cpp

moc_dcurve.cpp: includes/dpack.h \
		includes/dcurve.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) includes/dcurve.h -o moc_dcurve.cpp

moc_dsaver.cpp: includes/dpack.h \
		includes/dsaver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) includes/dsaver.h -o moc_dsaver.cpp

moc_dthread.cpp: includes/uhandler.h \
		includes/dpack.h \
		includes/dconfig.h \
		includes/dthread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) includes/dthread.h -o moc_dthread.cpp

moc_uhandler.cpp: includes/dpack.h \
		includes/uhandler.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) includes/uhandler.h -o moc_uhandler.cpp

moc_configdialog.cpp: ui_configdialog.h \
		includes/dconfig.h \
		newConfigDialog/configdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) newConfigDialog/configdialog.h -o moc_configdialog.cpp

moc_processdialog.cpp: includes/dthread.h \
		includes/uhandler.h \
		includes/dpack.h \
		includes/dconfig.h \
		includes/dcurve.h \
		includes/dsaver.h \
		ui_processdialog.h \
		processDialog/processdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) processDialog/processdialog.h -o moc_processdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_configdialog.h ui_processdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_configdialog.h ui_processdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_configdialog.h: newConfigDialog/configdialog.ui
	/usr/bin/uic-qt4 newConfigDialog/configdialog.ui -o ui_configdialog.h

ui_processdialog.h: processDialog/processdialog.ui
	/usr/bin/uic-qt4 processDialog/processdialog.ui -o ui_processdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mwindow.h \
		processDialog/processdialog.h \
		includes/dthread.h \
		includes/uhandler.h \
		includes/dpack.h \
		includes/dconfig.h \
		includes/dcurve.h \
		includes/dsaver.h \
		ui_processdialog.h \
		newConfigDialog/configdialog.h \
		ui_configdialog.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mwindow.o: mwindow.cpp mwindow.h \
		processDialog/processdialog.h \
		includes/dthread.h \
		includes/uhandler.h \
		includes/dpack.h \
		includes/dconfig.h \
		includes/dcurve.h \
		includes/dsaver.h \
		ui_processdialog.h \
		newConfigDialog/configdialog.h \
		ui_configdialog.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mwindow.o mwindow.cpp

dconfig.o: includes/dconfig.cpp includes/dconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dconfig.o includes/dconfig.cpp

dcurve.o: includes/dcurve.cpp includes/dcurve.h \
		includes/dpack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcurve.o includes/dcurve.cpp

dsaver.o: includes/dsaver.cpp includes/dsaver.h \
		includes/dpack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dsaver.o includes/dsaver.cpp

dthread.o: includes/dthread.cpp includes/dthread.h \
		includes/uhandler.h \
		includes/dpack.h \
		includes/dconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dthread.o includes/dthread.cpp

uhandler.o: includes/uhandler.cpp includes/uhandler.h \
		includes/dpack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uhandler.o includes/uhandler.cpp

configdialog.o: newConfigDialog/configdialog.cpp newConfigDialog/configdialog.h \
		ui_configdialog.h \
		includes/dconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o newConfigDialog/configdialog.cpp

processdialog.o: processDialog/processdialog.cpp processDialog/processdialog.h \
		includes/dthread.h \
		includes/uhandler.h \
		includes/dpack.h \
		includes/dconfig.h \
		includes/dcurve.h \
		includes/dsaver.h \
		ui_processdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processdialog.o processDialog/processdialog.cpp

moc_mwindow.o: moc_mwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mwindow.o moc_mwindow.cpp

moc_dcurve.o: moc_dcurve.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dcurve.o moc_dcurve.cpp

moc_dsaver.o: moc_dsaver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dsaver.o moc_dsaver.cpp

moc_dthread.o: moc_dthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dthread.o moc_dthread.cpp

moc_uhandler.o: moc_uhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uhandler.o moc_uhandler.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

moc_processdialog.o: moc_processdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_processdialog.o moc_processdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

